export type Article = {
  d: string
  sec: string
  t: string
  by: string | null
  th: Record<string, string[]>
}

export type ThemeConfig = {
  name: string
  subs: string[]
}

export const articles: Article[] = [
  {d:"2026-04-17",sec:"Opinion",t:"A.I.: Creativity Killer or Companion?",by:null,th:{"Society & Culture":["Creativity & taste"]}},
  {d:"2026-04-17",sec:"Technology",t:"How Do You Measure an A.I. Boom?",by:"Kevin Roose",th:{"AI Industry & Models":["Benchmarks & capability"]}},
  {d:"2026-04-17",sec:"DealBook",t:"Washington's Scramble to Get Anthropic's Powerful New Model",by:"Andrew Ross Sorkin et al.",th:{"Anthropic & Mythos":["Government response"],"Cybersecurity & Defense":["Offensive capability"]}},
  {d:"2026-04-17",sec:"Podcasts",t:"A.I. Backlash Turns Violent + Kara Swisher on Healthmaxxing + The Zuck Bot Is Coming",by:"Kevin Roose, Casey Newton et al.",th:{"Society & Culture":["Public backlash"],"AI Safety & Risks":["Model behavior"]}},
  {d:"2026-04-17",sec:"U.S.",t:"A Family Feud at an Oregon Winery Turns to Vinegar Over A.I. Slop",by:"Evan Gorelick, Anna Griffin",th:{"AI Misuse & Slop":["Hallucinations & errors"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-04-17",sec:"Arts",t:"With A.I. Glasses, Korea's Theaters Hope for a K-Pop Moment",by:"Hahna Yoon",th:{"Arts & Creative":["Performance & film"]}},
  {d:"2026-04-16",sec:"The Headlines",t:"Trump's Scattershot Week, and a Stock Market Record",by:"Tracy Mumford et al.",th:{"Business & Economy":["Markets & finance"]}},
  {d:"2026-04-16",sec:"Politics",t:"Talarico Leads a Democratic Cash Surge: 7 Takeaways From 2026 Filings",by:"Theodore Schleifer",th:{"Politics & Elections":["Midterms & campaigns"]}},
  {d:"2026-04-16",sec:"U.S.",t:"The First Statewide Ban on Data Centers Is on the Verge of Becoming Law",by:"Jenna Russell",th:{"Data Centers & Energy":["Local opposition"],"Legal & Regulation":["State legislation"]}},
  {d:"2026-04-15",sec:"U.S.",t:"Sneaker Company Allbirds Plans to Pivot to A.I. Yes, A.I.",by:"Livia Albeck-Ripka",th:{"Business & Economy":["Corporate pivots"]}},
  {d:"2026-04-15",sec:"Opinion",t:"It's the End of the Internet as We Know It",by:"Raffi Krikorian",th:{"Cybersecurity & Defense":["Vulnerabilities & patching"]}},
  {d:"2026-04-15",sec:"Opinion",t:"Iran Is Teaching Us Something About the American War Machine",by:"David Wallace-Wells",th:{"War & Military":["Iran conflict"]}},
  {d:"2026-04-15",sec:"Business",t:"Snap Is Laying Off 16% of Full-Time Staff as It Embraces A.I.",by:"Kailyn Rhone",th:{"Jobs & Labor":["Layoffs & cuts"]}},
  {d:"2026-04-15",sec:"Art & Design",t:"In the Tech Heart of Texas, an Art Show Built on Data, Code and A.I.",by:"Jillian Anthony",th:{"Arts & Creative":["Visual art & design"]}},
  {d:"2026-04-15",sec:"Business",t:"That Meeting You Hate May Keep A.I. From Stealing Your Job",by:"Noam Scheiber",th:{"Jobs & Labor":["Future of work"]}},
  {d:"2026-04-15",sec:"Technology",t:"How 'Jagged Intelligence' Can Reframe the A.I. Debate",by:"Cade Metz",th:{"AI Industry & Models":["Benchmarks & capability"],"Jobs & Labor":["Future of work"]}},
  {d:"2026-04-15",sec:"Personal Tech",t:"Spice Up Your Cooking Skills With Help From Your Phone",by:"J. D. Biersdorfer",th:{"Daily Life & Tools":[]}},
  {d:"2026-04-15",sec:"Opinion",t:"Don't Use A.I. to Do This",by:"Colson Whitehead",th:{"Society & Culture":["Creativity & taste"]}},
  {d:"2026-04-15",sec:"Magazine",t:"We Don't Really Know How A.I. Works. That's a Problem.",by:"Oliver Whang",th:{"AI Safety & Risks":["Interpretability & alignment"]}},
  {d:"2026-04-14",sec:"Technology",t:"Like Anthropic, OpenAI Will Share Latest Technology Only With Trusted Companies",by:"Cade Metz",th:{"Anthropic & Mythos":["Access & deployment"],"OpenAI":["Products & strategy"],"Cybersecurity & Defense":["Offensive capability"]}},
  {d:"2026-04-14",sec:"Podcasts",t:"Hard Fork Episode #189",by:null,th:{"AI Industry & Models":[]}},
  {d:"2026-04-14",sec:"Podcasts",t:"Why Is Everyone Spooked by Claude Mythos Preview?",by:"Casey Newton, Kevin Roose",th:{"Anthropic & Mythos":["Mythos launch"]}},
  {d:"2026-04-14",sec:"Podcasts",t:"Can Sam Altman Be Trusted?",by:"Ronan Farrow, Andrew Marantz",th:{"OpenAI":["Altman & leadership"]}},
  {d:"2026-04-14",sec:"The Daily",t:"The Workers Letting A.I. Do Their Jobs",by:"Natalie Kitroeff et al.",th:{"Jobs & Labor":["Coders & software"]}},
  {d:"2026-04-14",sec:"Opinion",t:"Why Aren't the Kids Out Protesting Against Trump?",by:"Thomas B. Edsall",th:{"Politics & Elections":["Trump administration"]}},
  {d:"2026-04-14",sec:"Opinion",t:"'I Don't Want a Person, I Want an A.I.'",by:null,th:{"Companions & Relationships":[]}},
  {d:"2026-04-14",sec:"Magazine",t:"I Feel So Sorry for My A.I. Sunglasses",by:"Sam Anderson",th:{"Daily Life & Tools":[]}},
  {d:"2026-04-14",sec:"Opinion",t:"Can a Bot Love You Back?",by:null,th:{"Companions & Relationships":[]}},
  {d:"2026-04-14",sec:"Opinion",t:"She Has an A.I. Boyfriend. Her Son Has Questions.",by:"Alexander Stockton, Francesca Trianni",th:{"Companions & Relationships":[]}},
  {d:"2026-04-14",sec:"Opinion",t:"She Has an A.I. Lover. Her Son Has Questions.",by:null,th:{"Companions & Relationships":[]}},
  {d:"2026-04-13",sec:"Technology",t:"Man Held in Attack on OpenAI Chief's Home Had List of A.I. Leaders, Officials Say",by:"Kalley Huang, Natallie Rocha",th:{"Society & Culture":["Public backlash"],"OpenAI":["Altman & leadership"]}},
  {d:"2026-04-13",sec:"Politics",t:"Trump Takes Down Post Depicting Himself as a Jesus-Like Figure",by:"Claire Moses",th:{"Politics & Elections":["Trump administration"]}},
  {d:"2026-04-13",sec:"Opinion",t:"I Went to China to See Its Progress on A.I. We Can't Beat It.",by:"Sebastian Mallaby",th:{"China & Geopolitics":[]}},
  {d:"2026-04-13",sec:"Well",t:"He Warned About the Dangers of A.I. If Only His Father Had Listened.",by:"Teddy Rosenbluth",th:{"Health & Medicine":[],"AI Safety & Risks":["Personal harm"]}},
  {d:"2026-04-12",sec:"Business",t:"The 'Annoyance Economy' Is More Than Just Annoying",by:"Lora Kelley",th:{"Business & Economy":["Markets & finance"]}},
  {d:"2026-04-12",sec:"Technology",t:"Mutually Automated Destruction: The Escalating Global A.I. Arms Race",by:"Sheera Frenkel et al.",th:{"War & Military":["Arms race & weapons"],"China & Geopolitics":[]}},
  {d:"2026-04-11",sec:"Opinion",t:"When Technology Outstrips Morality in War",by:null,th:{"War & Military":["Iran conflict"]}},
  {d:"2026-04-10",sec:"Business",t:"Banks Are Warned About Anthropic's New, Powerful A.I. Technology",by:"Rob Copeland, Colby Smith",th:{"Anthropic & Mythos":["Government response"],"Cybersecurity & Defense":["Offensive capability"]}},
  {d:"2026-04-10",sec:"U.S.",t:"Molotov Cocktail Is Hurled at Home of OpenAI C.E.O. Sam Altman",by:"Nicholas Bogel-Burroughs et al.",th:{"Society & Culture":["Public backlash"],"OpenAI":["Altman & leadership"]}},
  {d:"2026-04-10",sec:"Eat",t:"Have You Used A.I. Chatbots for Nutrition Advice?",by:"Alice Callahan",th:{"Health & Medicine":[]}},
  {d:"2026-04-10",sec:"DealBook",t:"Bessent and Powell's A.I. Anxiety",by:"Andrew Ross Sorkin et al.",th:{"Anthropic & Mythos":["Government response"],"Business & Economy":["Markets & finance"]}},
  {d:"2026-04-10",sec:"Podcasts",t:"Anthropic's Cybersecurity Shock Wave + Ronan Farrow and Andrew Marantz on Their Sam Altman Investigation",by:"Kevin Roose, Casey Newton et al.",th:{"Anthropic & Mythos":["Mythos launch"],"Cybersecurity & Defense":["Offensive capability"],"OpenAI":["Altman & leadership"]}},
  {d:"2026-04-10",sec:"Briefing",t:"You Can't Use This A.I.",by:"Evan Gorelick",th:{"Anthropic & Mythos":["Access & deployment"]}},
  {d:"2026-04-10",sec:"Books",t:"Where Does Publishing's A.I. Problem Leave Authors and Readers?",by:"Alexandra Alter",th:{"Arts & Creative":["Writing & publishing"],"AI Misuse & Slop":["Content fraud"]}},
  {d:"2026-04-09",sec:"U.S.",t:"Florida Investigates Whether ChatGPT Helped a Campus Shooting Suspect",by:"Patricia Mazzei",th:{"AI Safety & Risks":["Personal harm"],"OpenAI":["Products & strategy"]}},
  {d:"2026-04-09",sec:"Opinion",t:"What A.I. and D.E.I. Have in Common",by:"John McWhorter",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-04-09",sec:"Europe",t:"He Made a Gadget to Amuse Pets. Then He Turned to Killer Drones.",by:"Andrew E. Kramer",th:{"War & Military":["Drones & autonomy"]}},
  {d:"2026-04-09",sec:"Style",t:"Gen Z Is Using A.I., but Doesn't Feel Great About It",by:"Callie Holtermann",th:{"Society & Culture":["Young people"]}},
  {d:"2026-04-08",sec:"U.S.",t:"Ohio Man Is First to Be Federally Convicted for Deepfake Porn",by:"Rylee Kirk",th:{"AI Misuse & Slop":["Deepfakes & impersonation"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-04-08",sec:"Technology",t:"Federal Court Denies Anthropic's Motion to Lift 'Supply Chain Risk' Label",by:"Mike Isaac",th:{"Anthropic vs Pentagon":["Legal battle"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-04-08",sec:"Business",t:"Adam Back Denies He Is Satoshi Nakamoto in Response to Times Investigation",by:"Kailyn Rhone",th:{"Business & Economy":["Markets & finance"]}},
  {d:"2026-04-08",sec:"Technology",t:"Meta Unveils New A.I. Model, Its First From the Superintelligence Lab",by:"Eli Tan",th:{"AI Industry & Models":["New models & releases"]}},
  {d:"2026-04-08",sec:"Health",t:"Patients Are Using Chatbots to Fight Medical Bills, With Mixed Results",by:"Sarah Kwon",th:{"Health & Medicine":[]}},
  {d:"2026-04-08",sec:"Opinion",t:"Deepfake Nudes Are Haunting America's Teens",by:"Jessica Grose",th:{"AI Misuse & Slop":["Deepfakes & impersonation"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-04-08",sec:"Media",t:"ProPublica Journalists Strike for a Day, Partly Over A.I.",by:"Katie Robertson",th:{"Jobs & Labor":["Layoffs & cuts"]}},
  {d:"2026-04-08",sec:"The Headlines",t:"Trump Backs Down on Iran, and an A.I. 'Reckoning'",by:"Tracy Mumford et al.",th:{"Anthropic & Mythos":["Mythos launch"]}},
  {d:"2026-04-08",sec:"Opinion",t:"We Are Witnessing the Rise of a New Aristocracy",by:"Jennifer M. Harris",th:{"Business & Economy":["Inequality & wealth"],"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-04-08",sec:"Real Estate",t:"In Search of Career Prospects, Young New Yorkers Turn to Construction",by:"Emily Lang, Karsten Moran",th:{"Jobs & Labor":["Young workers & grads"]}},
  {d:"2026-04-07",sec:"Opinion",t:"Anthropic's Restraint Is a Terrifying Warning Sign",by:"Thomas L. Friedman",th:{"Anthropic & Mythos":["Mythos launch"],"AI Safety & Risks":["Existential & systemic"]}},
  {d:"2026-04-07",sec:"Technology",t:"Anthropic Claims Its New A.I. Model, Mythos, Is a Cybersecurity 'Reckoning'",by:"Kevin Roose",th:{"Anthropic & Mythos":["Mythos launch"],"Cybersecurity & Defense":["Offensive capability"]}},
  {d:"2026-04-07",sec:"Opinion",t:"Human Writers Who Rage Against A.I.",by:null,th:{"Arts & Creative":["Writing & publishing"]}},
  {d:"2026-04-07",sec:"Opinion",t:"Now We Know What a Modern War Looks Like",by:"Lloyd J. Austin III",th:{"War & Military":["Iran conflict"]}},
  {d:"2026-04-07",sec:"Technology",t:"How Accurate Are Google's A.I. Overviews?",by:"Tripp Mickle et al.",th:{"AI Industry & Models":["Benchmarks & capability"]}},
  {d:"2026-04-06",sec:"Podcasts",t:"Hard Fork Episode #188",by:null,th:{"AI Industry & Models":[]}},
  {d:"2026-04-06",sec:"Technology",t:"A.I. Is on Its Way to Upending Cybersecurity",by:"Cade Metz, Kate Conger",th:{"Cybersecurity & Defense":["Vulnerabilities & patching"]}},
  {d:"2026-04-06",sec:"Technology",t:"The Big Bang: A.I. Has Created a Code Overload",by:"Mike Isaac, Erin Griffith",th:{"Jobs & Labor":["Coders & software"]}},
  {d:"2026-04-06",sec:"Opinion",t:"Teaching in an American University Is Very Strange Right Now",by:"Frank Bruni",th:{"Education":[]}},
  {d:"2026-04-06",sec:"Magazine",t:"Forget the A.I. Apocalypse. Memes Have Already Nuked Our Culture.",by:"Willy Staley",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-04-06",sec:"Opinion",t:"This Is What Will Ruin Public Opinion Polling for Good",by:"Leif Weatherby, Benjamin Recht",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-04-05",sec:"World",t:"A Looming Deadline (Strait of Hormuz)",by:"Katrin Bennhold",th:{"War & Military":["Iran conflict"]}},
  {d:"2026-04-05",sec:"Opinion",t:"Iran Is Ending the Dream of Remote-Controlled War",by:"Marc Gustafson, Justin Kosslyn",th:{"War & Military":["Iran conflict"]}},
  {d:"2026-04-04",sec:"Technology",t:"What Teens Are Doing With Those Role-Playing Chatbots",by:"Kashmir Hill, Frances F. Denny",th:{"Companions & Relationships":[],"Society & Culture":["Young people"]}},
  {d:"2026-04-04",sec:"DealBook",t:"Trump Slashed Science Funding. Now the U.S. Could Face a Costly Brain Drain.",by:"Vivienne Walt",th:{"Politics & Elections":["Trump administration"]}},
  {d:"2026-04-03",sec:"Business",t:"Big Banks Seeking a Piece of SpaceX's I.P.O. Must Subscribe to Elon Musk's Grok",by:"Maureen Farrell",th:{"Business & Economy":["Markets & finance"],"AI Industry & Models":["Products & strategy"]}},
  {d:"2026-04-03",sec:"Opinion",t:"The Rise and Fall of Pam Bondi",by:null,th:{"Politics & Elections":["Trump administration"]}},
  {d:"2026-04-03",sec:"Podcasts",t:"The Future of Addictive Design + Going Deep at DeepMind + HatGPT",by:"Kevin Roose, Casey Newton et al.",th:{"AI Industry & Models":[]}},
  {d:"2026-04-03",sec:"Business",t:"Economists Once Dismissed the A.I. Job Threat, but Not Anymore",by:"Ben Casselman",th:{"Jobs & Labor":["Future of work"]}},
  {d:"2026-04-02",sec:"Technology",t:"OpenAI Buys Streaming Show 'TBPN,' Aiming to Change Narrative on A.I.",by:"Mike Isaac",th:{"OpenAI":["Products & strategy"]}},
  {d:"2026-04-02",sec:"Opinion",t:"Eloquence Has Grown Passé. Let's Bring It Back Into Fashion.",by:"John McWhorter",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-04-02",sec:"Magazine",t:"Worried About A.I. Taking Your Job? That's Not Very 'Agentic' of You.",by:"Nitsuh Abebe",th:{"Jobs & Labor":["Future of work"]}},
  {d:"2026-04-02",sec:"Technology",t:"How A.I. Helped One Man (and His Brother) Build a $1.8 Billion Company",by:"Erin Griffith",th:{"Business & Economy":["Startups & VC"],"Jobs & Labor":["Tiny teams"]}},
  {d:"2026-04-02",sec:"Technology",t:"A.I. Could Change the World. But First It Is Changing Silicon Valley.",by:"Kalley Huang",th:{"Jobs & Labor":["Coders & software"]}},
  {d:"2026-04-02",sec:"Live",t:"Doctors Couldn't Help Them. They Rolled the Dice With A.I.",by:"Maggie Astor",th:{"Health & Medicine":[]}},
  {d:"2026-04-01",sec:"Technology",t:"A.I. Companies Shatter Fund-Raising Records, as Boom Accelerates",by:"Erin Griffith",th:{"Business & Economy":["Startups & VC"]}},
  {d:"2026-04-01",sec:"Technology",t:"SpaceX Files to Go Public, Setting Stage for Huge I.P.O.",by:"Ryan Mac et al.",th:{"Business & Economy":["Markets & finance"]}},
  {d:"2026-04-01",sec:"Science",t:"Can Science Predict When a Study Won't Hold Up?",by:"Carl Zimmer",th:{"AI Industry & Models":["Benchmarks & capability"]}},
  {d:"2026-04-01",sec:"Opinion",t:"All the Worst People Seem to Want to Be 'High Agency'",by:"Sophie Haigney",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-03-31",sec:"Technology",t:"OpenAI Adds Another $12 Billion to Latest Funding Round",by:"Cade Metz",th:{"OpenAI":["Products & strategy"],"Business & Economy":["Startups & VC"]}},
  {d:"2026-03-31",sec:"Asia Pacific",t:"When Will Japan's Cherry Blossoms Bloom? A.I. Can Help Answer That",by:"Javier C. Hernández et al.",th:{"Daily Life & Tools":[]}},
  {d:"2026-03-30",sec:"Technology",t:"What to Know About California's Executive Order on A.I.",by:"Cecilia Kang",th:{"Legal & Regulation":["State legislation"]}},
  {d:"2026-03-30",sec:"U.S.",t:"Woman Spent Five Months in Jail After A.I. Linked Her to Bank Fraud Case",by:"Michael Levenson",th:{"AI Safety & Risks":["Personal harm"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-03-30",sec:"Technology",t:"States Plow Ahead With A.I. Regulation, Defying Trump",by:"Cecilia Kang",th:{"Legal & Regulation":["State legislation"]}},
  {d:"2026-03-30",sec:"Paid Post",t:"Amid the Noise and Chaos of Tech Trade Shows, Ambient Intelligence Faces Its Real Test",by:null,th:{"AI Industry & Models":[]}},
  {d:"2026-03-29",sec:"Business",t:"New Political Group to Push Trump's A.I. Agenda in Midterms",by:"Theodore Schleifer",th:{"Politics & Elections":["Midterms & campaigns"]}},
  {d:"2026-03-29",sec:"Opinion",t:"Your Chatbot Isn't a Therapist",by:"Divya Saini, Natasha Bailen",th:{"Health & Medicine":[],"Companions & Relationships":[]}},
  {d:"2026-03-29",sec:"Opinion",t:"I Saw Something New in San Francisco",by:"Ezra Klein",th:{"Society & Culture":["Discourse & ideas"],"Anthropic & Mythos":["Mythos launch"]}},
  {d:"2026-03-28",sec:"Business",t:"In an Asymmetrical War, Iran Seeks an Edge With Its Information War",by:"Steven Lee Myers et al.",th:{"War & Military":["Iran conflict"],"AI Misuse & Slop":["Deepfakes & impersonation"]}},
  {d:"2026-03-28",sec:"Business",t:"Smaller Is Better in Silicon Valley's 'Tiny Team' Moment",by:"Lora Kelley",th:{"Jobs & Labor":["Tiny teams"]}},
  {d:"2026-03-27",sec:"Briefing",t:"Your Suck-up Chatbot",by:"Sam Sifton",th:{"AI Safety & Risks":["Model behavior"]}},
  {d:"2026-03-27",sec:"Podcasts",t:"The Ezra Klein Show: How Fast Will A.I. Agents Rip Through the Economy?",by:"Ezra Klein, Rollin Hu",th:{"Jobs & Labor":["Future of work"],"Anthropic & Mythos":["Access & deployment"]}},
  {d:"2026-03-27",sec:"Opinion",t:"It's Musk's World Now",by:"Quinn Slobodian et al.",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-03-27",sec:"Opinion",t:"There's a Good Reason You Can't Concentrate",by:"Cal Newport",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-03-26",sec:"Technology",t:"Judge Stays Pentagon's Labeling of Anthropic as 'Supply Chain Risk'",by:"Mike Isaac",th:{"Anthropic vs Pentagon":["Legal battle"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-03-26",sec:"Mind",t:"Seeking a Sounding Board? Beware the Eager-to-Please Chatbot.",by:"Teddy Rosenbluth",th:{"AI Safety & Risks":["Model behavior"]}},
  {d:"2026-03-26",sec:"Economy",t:"Local Opposition Is Slowing A.I. Data Centers. Wall Street Has Noticed.",by:"Lydia DePillis",th:{"Data Centers & Energy":["Local opposition"]}},
  {d:"2026-03-26",sec:"DealBook",t:"Shield AI, a Start-Up Making Military Drones, Raises $2 Billion",by:"Michael J. de la Merced",th:{"War & Military":["Drones & autonomy"],"Business & Economy":["Startups & VC"]}},
  {d:"2026-03-26",sec:"Movies",t:"A Documentary About A.I. Gets Chief Executives on the Record",by:"Alissa Wilkinson",th:{"Arts & Creative":["Performance & film"]}},
  {d:"2026-03-25",sec:"Politics",t:"Melania and the Robot",by:"Katie Rogers",th:{"Education":[],"Politics & Elections":["Trump administration"]}},
  {d:"2026-03-25",sec:"Technology",t:"Meta Lays Off 700 Employees, While Rewarding Top Executives",by:"Eli Tan",th:{"Jobs & Labor":["Layoffs & cuts"]}},
  {d:"2026-03-25",sec:"DealBook",t:"What Sora's End Says About OpenAI's Strategy",by:"Andrew Ross Sorkin et al.",th:{"OpenAI":["Products & strategy"]}},
  {d:"2026-03-25",sec:"Opinion",t:"The 'Shy Girl' Fiasco Shows Why Trust in Writers Is Plummeting",by:"Andrea Bartz",th:{"Arts & Creative":["Writing & publishing"],"AI Misuse & Slop":["Content fraud"]}},
  {d:"2026-03-25",sec:"Arts",t:"The Anomaly of Humanity as A.I. Grows Inevitable",by:"Yussef Cole",th:{"Arts & Creative":["Visual art & design"]}},
  {d:"2026-03-24",sec:"Technology",t:"OpenAI Is Shutting Down Sora, Its A.I. Video Generator",by:"Cade Metz",th:{"OpenAI":["Products & strategy"]}},
  {d:"2026-03-24",sec:"Podcasts",t:"When a Company's Biggest Expense Is A.I.",by:"Casey Newton, Kevin Roose",th:{"Business & Economy":["Markets & finance"],"Jobs & Labor":["Future of work"]}},
  {d:"2026-03-24",sec:"Podcasts",t:"Block Uses A.I. as Excuse for Laying off 40% of the Company",by:"Casey Newton, Kevin Roose",th:{"Jobs & Labor":["Layoffs & cuts"]}},
  {d:"2026-03-24",sec:"Technology",t:"Arm Holdings, in Break From Past, Will Sell Its Own Computer Chips",by:"Don Clark",th:{"AI Industry & Models":["Chips & hardware"]}},
  {d:"2026-03-24",sec:"New York",t:"In N.Y.C. Classes, Teachers Can Use A.I. to Plan but Not to Assign Grades",by:"Matthew Haag",th:{"Education":[]}},
  {d:"2026-03-24",sec:"Style",t:"What's With All the A.I. Videos of Cheating Fruit?",by:"Madison Malone Kircher",th:{"AI Misuse & Slop":["Content fraud"],"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-03-24",sec:"Economy",t:"Young Graduates Face the Grimmest Job Market in Years",by:"Sydney Ember",th:{"Jobs & Labor":["Young workers & grads"]}},
  {d:"2026-03-23",sec:"Opinion",t:"The New Moneyed Interests: Crypto and A.I.",by:"E.J. Dionne Jr.",th:{"Politics & Elections":["Lobbying & money"]}},
  {d:"2026-03-23",sec:"Economy",t:"Trump Sets Up 'Pax Silica' Fund to Reduce Global Dependencies",by:"Ana Swanson, Sheera Frenkel",th:{"Politics & Elections":["Trump administration"],"China & Geopolitics":[]}},
  {d:"2026-03-22",sec:"Opinion",t:"Bracing for the A.I. Economy to Come",by:null,th:{"Jobs & Labor":["Future of work"]}},
  {d:"2026-03-22",sec:"Style",t:"Is Taste the One Thing A.I. Can't Replace?",by:"Joseph Bernstein",th:{"Society & Culture":["Creativity & taste"],"Jobs & Labor":["Future of work"]}},
  {d:"2026-03-21",sec:"Opinion",t:"Let-It-Rip Jeremy vs. Sneaky Sam",by:"Maureen Dowd",th:{"OpenAI":["Altman & leadership"]}},
  {d:"2026-03-20",sec:"Politics",t:"White House Unveils A.I. Policy Aimed at Blocking State Laws",by:"Cecilia Kang",th:{"Legal & Regulation":["Federal policy"],"Politics & Elections":["Trump administration"]}},
  {d:"2026-03-20",sec:"Technology",t:"More! More! More! Tech Workers Max Out Their A.I. Use.",by:"Kevin Roose",th:{"Jobs & Labor":["Coders & software"],"Daily Life & Tools":[]}},
  {d:"2026-03-20",sec:"Podcasts",t:"'A.I.-Washing' Layoffs? + Why L.L.M.s Can't Write Well + Tokenmaxxing",by:"Kevin Roose, Casey Newton et al.",th:{"Jobs & Labor":["Layoffs & cuts"]}},
  {d:"2026-03-20",sec:"Media",t:"Can Jonah Peretti Save BuzzFeed From Extinction?",by:"Benjamin Mullin",th:{"Business & Economy":["Corporate pivots"]}},
  {d:"2026-03-19",sec:"Technology",t:"U.S. Says 3 Tied to Silicon Valley Server Maker Broke Export Laws",by:"Kalley Huang, Ana Swanson",th:{"China & Geopolitics":[],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-03-19",sec:"Books",t:"A.I. Is Writing Fiction. Publishers Are Unprepared.",by:"Alexandra Alter",th:{"Arts & Creative":["Writing & publishing"],"AI Misuse & Slop":["Content fraud"]}},
  {d:"2026-03-19",sec:"Technology",t:"Jeff Bezos in Talks to Raise $100 Billion Fund to Transform Companies With A.I.",by:"Cade Metz, Karen Weise",th:{"Business & Economy":["Startups & VC"]}},
  {d:"2026-03-19",sec:"Books",t:"Horror Novel 'Shy Girl' Canceled Over Suspected A.I. Use",by:"Alexandra Alter",th:{"Arts & Creative":["Writing & publishing"],"AI Misuse & Slop":["Content fraud"]}},
  {d:"2026-03-19",sec:"Technology",t:"Have You Turned to A.I. For Advice on a Romantic Relationship?",by:"Kashmir Hill",th:{"Companions & Relationships":[]}},
  {d:"2026-03-19",sec:"Economy",t:"Extended Mideast Conflict Would Slow Trade and Growth, W.T.O. Warns",by:"Ana Swanson",th:{"War & Military":["Iran conflict"],"Business & Economy":["Markets & finance"]}},
  {d:"2026-03-19",sec:"Technology",t:"The Long Farewell to Mark Zuckerberg's Metaverse",by:"Eli Tan, Mike Isaac",th:{"AI Industry & Models":["Products & strategy"]}},
  {d:"2026-03-19",sec:"Art & Design",t:"The New Museum Reopens, Asking, 'What Is Human?'",by:"Jason Farago, Elliott Jerome Brown Jr.",th:{"Arts & Creative":["Visual art & design"]}},
  {d:"2026-03-19",sec:"Wine, Beer & Cocktails",t:"A.I. Is Coming for the Sommeliers",by:"Eric Asimov",th:{"Daily Life & Tools":[],"Jobs & Labor":["Future of work"]}},
  {d:"2026-03-19",sec:"Business",t:"Sorry, Mom. You're Chatting With an A.I. Agent, Not Your Son.",by:"Natallie Rocha, Arsenii Vaselenko",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-03-19",sec:"Technology",t:"A.I. Agents: They're Fun. They're Useful. But Don't Give Them the Credit Card.",by:"Cade Metz",th:{"AI Industry & Models":["Agents"],"AI Safety & Risks":["Model behavior"]}},
  {d:"2026-03-18",sec:"Movies",t:"A.I. Replica of Val Kilmer to Appear in Film After His Death",by:"Reggie Ugwu",th:{"Arts & Creative":["Performance & film"]}},
  {d:"2026-03-18",sec:"Technology",t:"Silicon Valley Musters Behind-the-Scenes Support for Anthropic",by:"Mike Isaac",th:{"Anthropic vs Pentagon":["Industry & politics"]}},
  {d:"2026-03-18",sec:"Energy & Environment",t:"Why Tech Giants Are Ditching the Power Grid",by:"Rebecca F. Elliott, Harry Stevens",th:{"Data Centers & Energy":["Power & grid"]}},
  {d:"2026-03-18",sec:"Technology",t:"Google Sits Pretty as A.I. Rivals Compete for Pentagon Favor",by:"Kate Conger, Julian E. Barnes",th:{"Anthropic vs Pentagon":["Industry & politics"],"War & Military":["Defense contracts"]}},
  {d:"2026-03-18",sec:"Technology",t:"Silicon Valley Bet on War. The Bets Are Paying Off.",by:"Sheera Frenkel",th:{"War & Military":["Defense contracts"],"Business & Economy":["Startups & VC"]}},
  {d:"2026-03-18",sec:"Economy",t:"The Cost of the A.I. Boom: A Trade Deficit the President Detests",by:"Ana Swanson",th:{"Business & Economy":["Markets & finance"]}},
  {d:"2026-03-18",sec:"Elections",t:"Stratton Wins and AIPAC's Power Is Tested: 4 Illinois Takeaways",by:"Shane Goldmacher",th:{"Politics & Elections":["Midterms & campaigns"]}},
  {d:"2026-03-17",sec:"Technology",t:"U.S. Says Anthropic Is an 'Unacceptable' National Security Risk",by:"Sheera Frenkel",th:{"Anthropic vs Pentagon":["Supply-chain-risk label"]}},
  {d:"2026-03-17",sec:"Technology",t:"China Ramps Up Scrutiny of a Meta A.I. Deal",by:"Ana Swanson et al.",th:{"China & Geopolitics":[]}},
  {d:"2026-03-17",sec:"Elections",t:"Illinois Primaries Flooded With Money From AIPAC and Cryptocurrency",by:"Matt Zdun",th:{"Politics & Elections":["Lobbying & money"]}},
  {d:"2026-03-17",sec:"Technology",t:"Netanyahu Posts 'Proof of Life' Video as A.I. Sows Doubts About What's Real",by:"Stuart A. Thompson, Tiffany Hsu",th:{"AI Misuse & Slop":["Deepfakes & impersonation"]}},
  {d:"2026-03-17",sec:"Business",t:"China Is Embracing OpenClaw, a New A.I. Agent, and the Government Is Wary",by:"Meaghan Tobin, Xinyun Wu",th:{"China & Geopolitics":[],"AI Industry & Models":["Agents"]}},
  {d:"2026-03-17",sec:"Europe",t:"Peter Thiel Fears the Antichrist Is Coming. In Rome, Some Call His View Heresy.",by:"Elisabetta Povoledo",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-03-17",sec:"Opinion",t:"'Surveil, Govern and Control': What Could Go Wrong?",by:"Thomas B. Edsall",th:{"Politics & Elections":["Trump administration"],"AI Safety & Risks":["Existential & systemic"]}},
  {d:"2026-03-17",sec:"New York",t:"In Rural New York, Some See Proposed A.I. Center as a Needless Intrusion",by:"Mark Sommer",th:{"Data Centers & Energy":["Local opposition"]}},
  {d:"2026-03-16",sec:"Technology",t:"Nvidia Built the A.I. Era. Now It Has to Defend It.",by:"Kalley Huang, Tripp Mickle",th:{"AI Industry & Models":["Chips & hardware"]}},
  {d:"2026-03-16",sec:"Podcasts",t:"Are Workers Suffering From A.I. Brain Fry?",by:"Casey Newton, Kevin Roose",th:{"Jobs & Labor":["Coders & software"]}},
  {d:"2026-03-16",sec:"Technology",t:"How Trump Drove a Wedge Between Florida Republicans Over A.I.",by:"David McCabe, Patricia Mazzei",th:{"Politics & Elections":["Trump administration"],"Legal & Regulation":["State legislation"]}},
  {d:"2026-03-16",sec:"Opinion",t:"Weighing Risks vs. Gains in Iran",by:null,th:{"War & Military":["Iran conflict"]}},
  {d:"2026-03-16",sec:"Opinion",t:"I Predicted the 2008 Financial Crisis. What Is Coming May Be Worse.",by:"Richard Bookstaber",th:{"Business & Economy":["Markets & finance"],"AI Safety & Risks":["Existential & systemic"]}},
  {d:"2026-03-14",sec:"Media",t:"Cascade of A.I. Fakes About War With Iran Causes Chaos Online",by:"Stuart A. Thompson, Alexander Cardia",th:{"AI Misuse & Slop":["Deepfakes & impersonation"],"War & Military":["Iran conflict"]}},
  {d:"2026-03-13",sec:"Politics",t:"The Age of Eerie A.I. Political Ads Is Here",by:"Katie Glueck",th:{"Politics & Elections":["Midterms & campaigns"],"AI Misuse & Slop":["Deepfakes & impersonation"]}},
  {d:"2026-03-13",sec:"Opinion",t:"Why I'm Suing Grammarly",by:"Julia Angwin",th:{"AI Misuse & Slop":["Deepfakes & impersonation"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-03-13",sec:"Business",t:"Are You Using A.I. at Work? We Want to Hear From You.",by:"Noam Scheiber",th:{"Jobs & Labor":["Future of work"]}},
  {d:"2026-03-13",sec:"Technology",t:"U.S. Tech Giants Flocked to the Persian Gulf. Now They Are Targets.",by:"Adam Satariano, Paul Mozur",th:{"War & Military":["Iran conflict"],"Business & Economy":["Markets & finance"]}},
  {d:"2026-03-13",sec:"Podcasts",t:"A.I. Goes to War + Is 'A.I. Brain Fry' Real? + How Grammarly Stole Casey's Identity",by:"Kevin Roose, Casey Newton et al.",th:{"War & Military":["Iran conflict"],"Jobs & Labor":["Coders & software"]}},
  {d:"2026-03-12",sec:"Technology",t:"Meta Delays Rollout of New A.I. Model After Performance Concerns",by:"Eli Tan",th:{"AI Industry & Models":["New models & releases"]}},
  {d:"2026-03-12",sec:"Europe",t:"Ukraine to Make Drone Videos Available for Training A.I. Models",by:"Andrew E. Kramer",th:{"War & Military":["Drones & autonomy"]}},
  {d:"2026-03-12",sec:"U.S.",t:"People in This Mississippi City Faced Off With Elon Musk. They Lost.",by:"Emily Cochrane",th:{"Data Centers & Energy":["Local opposition"]}},
  {d:"2026-03-12",sec:"U.S.",t:"Ron DeSantis Wants Speedy Executions, and Lots of Them",by:"Adam Liptak",th:{"Politics & Elections":["Trump administration"]}},
  {d:"2026-03-12",sec:"Personal Tech",t:"A.I. Chatbots Want Your Health Records. Tread Carefully.",by:"Brian X. Chen, Teddy Rosenbluth",th:{"Health & Medicine":[]}},
  {d:"2026-03-12",sec:"Technology",t:"A.I. Writes Buggy Code. A Silicon Valley Start-Up Wants to Fix It.",by:"Cade Metz",th:{"AI Industry & Models":["Benchmarks & capability"]}},
  {d:"2026-03-12",sec:"Technology",t:"Silicon Valley's Image Takes a Dark Turn in Pop Culture",by:"Erin Griffith",th:{"Society & Culture":["Discourse & ideas"],"Arts & Creative":["Performance & film"]}},
  {d:"2026-03-12",sec:"Magazine",t:"Coding After Coders: The End of Computer Programming as We Know It",by:"Clive Thompson",th:{"Jobs & Labor":["Coders & software"]}},
  {d:"2026-03-12",sec:"Opinion",t:"The Democrats Could Still Mess This Up",by:null,th:{"Politics & Elections":["Midterms & campaigns"]}},
  {d:"2026-03-11",sec:"Opinion",t:"Teens Are Falling Out of Love With Tech",by:"Jessica Grose",th:{"Society & Culture":["Young people"]}},
  {d:"2026-03-11",sec:"DealBook",t:"Microsoft Takes a Stand Against the Trump Administration",by:"Andrew Ross Sorkin et al.",th:{"Anthropic vs Pentagon":["Industry & politics"]}},
  {d:"2026-03-11",sec:"Magazine",t:"X's Chatbot Started Undressing Women. Was This What A.I. Wanted All Along?",by:"Mitch Therieau",th:{"AI Misuse & Slop":["Deepfakes & impersonation"]}},
  {d:"2026-03-10",sec:"Politics",t:"ChatGPT, Other Chatbots Approved for Official Use in the Senate",by:"Catie Edmondson",th:{"Politics & Elections":["Government use"],"OpenAI":["Products & strategy"]}},
  {d:"2026-03-10",sec:"Canada",t:"Mother of British Columbia Shooting Victim Sues OpenAI",by:"Vjosa Isai",th:{"OpenAI":["Products & strategy"],"AI Safety & Risks":["Personal harm"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-03-10",sec:"Technology",t:"Meta Acquires Moltbook, the Social Network Just for A.I. Bots",by:"Cade Metz",th:{"AI Industry & Models":["Products & strategy"]}},
  {d:"2026-03-10",sec:"Technology",t:"A.I. Incites a New Wave of Grieving Parents Fighting for Online Safety",by:"Cecilia Kang",th:{"AI Safety & Risks":["Personal harm"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-03-10",sec:"Technology",t:"Tell Us: How Are You Using A.I. for the Tasks of Daily Life?",by:"Elie Levine",th:{"Daily Life & Tools":[]}},
  {d:"2026-03-10",sec:"Technology",t:"YouTube Adds Tool to Help Public Figures Report Fake Videos",by:"Natallie Rocha",th:{"AI Misuse & Slop":["Deepfakes & impersonation"]}},
  {d:"2026-03-10",sec:"Opinion",t:"How 6,000 Bad Coding Lessons Turned a Chatbot Evil",by:"Dan Kagan-Kans",th:{"AI Safety & Risks":["Model behavior"]}},
  {d:"2026-03-10",sec:"Technology",t:"Former Meta A.I. Chief's Start-Up Is Valued at $3.5 Billion",by:"Cade Metz",th:{"AI Industry & Models":["Products & strategy"],"Business & Economy":["Startups & VC"]}},
  {d:"2026-03-09",sec:"Podcasts",t:"The Consumer Backlash to OpenAI",by:null,th:{"OpenAI":["Products & strategy"],"Anthropic vs Pentagon":["Industry & politics"]}},
  {d:"2026-03-09",sec:"Media",t:"An Amish Avatar and an A.I. Monk Are Pitching Supplements on Social Media",by:"Ken Bensinger et al.",th:{"AI Misuse & Slop":["Content fraud"]}},
  {d:"2026-03-09",sec:"Technology",t:"Anthropic Sues Pentagon Over 'Supply Chain Risk' Label",by:"Sheera Frenkel",th:{"Anthropic vs Pentagon":["Legal battle"],"Legal & Regulation":["Courts & lawsuits"]}},
  {d:"2026-03-09",sec:"The Daily",t:"Anthropic vs. the Pentagon: Inside the Battle Over A.I. Warfare",by:"Natalie Kitroeff et al.",th:{"Anthropic vs Pentagon":["Negotiations & breakdown"],"War & Military":["Defense contracts"]}},
  {d:"2026-03-09",sec:"Business",t:"Who's a Better Writer: A.I. or Humans? Take Our Quiz.",by:"Kevin Roose, Stuart A. Thompson",th:{"Arts & Creative":["Writing & publishing"]}},
  {d:"2026-03-09",sec:"Business",t:"The Former Coal Miner in the Middle of the A.I. Data Center Boom",by:"Adam Satariano",th:{"Data Centers & Energy":["Real estate & capital"]}},
  {d:"2026-03-08",sec:"Opinion",t:"The Future We Feared Is Already Here",by:"Ezra Klein",th:{"Anthropic vs Pentagon":["Commentary & opinion"],"AI Safety & Risks":["Existential & systemic"]}},
  {d:"2026-03-07",sec:"Arts",t:"When DOGE Unleashed ChatGPT on the Humanities",by:"Jennifer Schuessler",th:{"Politics & Elections":["Trump administration"],"OpenAI":["Products & strategy"]}},
  {d:"2026-03-07",sec:"DealBook",t:"Big Tech's Uncertain Future in the Persian Gulf",by:"Vivienne Walt",th:{"War & Military":["Iran conflict"],"Business & Economy":["Markets & finance"]}},
  {d:"2026-03-07",sec:"Technology",t:"For OpenAI and Anthropic, the Competition Is Deeply Personal",by:"Mike Isaac",th:{"OpenAI":["Altman & leadership"],"Anthropic vs Pentagon":["Industry & politics"]}},
  {d:"2026-03-07",sec:"Technology",t:"A Guide to the Pentagon's Dance With Anthropic and OpenAI",by:"Cade Metz",th:{"Anthropic vs Pentagon":["Negotiations & breakdown"],"OpenAI":["Products & strategy"]}},
  {d:"2026-03-07",sec:"Magazine",t:"Are A.I.-Generated Videos Changing How We See Animals?",by:"Sophie Haigney",th:{"AI Misuse & Slop":["Content fraud"],"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-03-07",sec:"Politics",t:"How Candidates Are Using Winks and Posts to Seek Crypto and A.I. Cash",by:"Shane Goldmacher, Leo Dominguez",th:{"Politics & Elections":["Lobbying & money"]}},
  {d:"2026-03-06",sec:"Opinion",t:"The Pentagon's Attack on Anthropic Is Political",by:null,th:{"Anthropic vs Pentagon":["Commentary & opinion"]}},
  {d:"2026-03-06",sec:"Opinion",t:"The Government's A.I. Alignment Problem",by:null,th:{"Anthropic vs Pentagon":["Commentary & opinion"]}},
  {d:"2026-03-06",sec:"Podcasts",t:"OpenAI's Fog of War + Betting on Iran + Hard Fork Review of Slop",by:"Kevin Roose, Casey Newton et al.",th:{"OpenAI":["Products & strategy"],"War & Military":["Iran conflict"]}},
  {d:"2026-03-06",sec:"Opinion",t:"Why the Pentagon Wants to Destroy Anthropic",by:"Ezra Klein, Rollin Hu",th:{"Anthropic vs Pentagon":["Commentary & opinion"]}},
  {d:"2026-03-06",sec:"Opinion",t:"Who Should Control A.I.?",by:"'The Ezra Klein Show'",th:{"Anthropic vs Pentagon":["Commentary & opinion"]}},
  {d:"2026-03-06",sec:"Opinion",t:"America Cannot Withstand the Economic Shock That's Coming",by:"Gina Raimondo",th:{"Jobs & Labor":["Future of work"],"Business & Economy":["Inequality & wealth"]}},
  {d:"2026-03-05",sec:"Technology",t:"Pentagon Officially Notifies Anthropic It Is a 'Supply Chain Risk'",by:"Cade Metz et al.",th:{"Anthropic vs Pentagon":["Supply-chain-risk label"]}},
  {d:"2026-03-05",sec:"Middle East",t:"A.I. Videos Distort Damage From Iranian Strikes",by:"Arijeta Lajka et al.",th:{"AI Misuse & Slop":["Deepfakes & impersonation"],"War & Military":["Iran conflict"]}},
  {d:"2026-03-05",sec:"Climate",t:"Feeling the Effects of 260,000 Federal Jobs Lost",by:"Claire Brown",th:{"Politics & Elections":["Trump administration"]}},
  {d:"2026-03-05",sec:"Technology",t:"Meet the A.I. Prospectors Tapping a Billion-Dollar Gusher",by:"Tripp Mickle, Tim Gruber",th:{"Data Centers & Energy":["Real estate & capital"]}},
  {d:"2026-03-05",sec:"Personal Tech",t:"The Smart Home Never Quite Worked. Now It's Getting an A.I. Reboot.",by:"Brian X. Chen",th:{"Daily Life & Tools":[]}},
  {d:"2026-03-05",sec:"DealBook",t:"Can Anthropic Make Peace With the Pentagon?",by:"Andrew Ross Sorkin et al.",th:{"Anthropic vs Pentagon":["Negotiations & breakdown"]}},
  {d:"2026-03-05",sec:"Technology",t:"A Word to the Wise: Don't Trust A.I. to File Your Taxes",by:"Stuart A. Thompson",th:{"AI Industry & Models":["Benchmarks & capability"],"Daily Life & Tools":[]}},
  {d:"2026-03-05",sec:"Opinion",t:"Mass Hysteria. Thousands of Jobs Lost. Just How Bad Is It Going to Get?",by:"Michael Steinberger",th:{"Jobs & Labor":["Future of work"]}},
  {d:"2026-03-05",sec:"Business",t:"What the Extraordinary Market Volatility in Asia Says About Energy and A.I.",by:"Meaghan Tobin",th:{"Data Centers & Energy":["Power & grid"],"Business & Economy":["Markets & finance"]}},
  {d:"2026-03-04",sec:"Asia Pacific",t:"China Bets on Technology to Resist U.S. Pressure",by:"Chris Buckley, Lily Kuo",th:{"China & Geopolitics":[]}},
  {d:"2026-03-04",sec:"Technology",t:"Trump Announces A.I. Industry Pledge to Pay for Power",by:"David McCabe, Brad Plumer",th:{"Data Centers & Energy":["Power & grid"],"Politics & Elections":["Trump administration"]}},
  {d:"2026-03-04",sec:"Opinion",t:"Data Centers Are a Distraction. The Real Fight Is Elsewhere.",by:"David Wallace-Wells",th:{"Data Centers & Energy":["Power & grid"]}},
  {d:"2026-03-04",sec:"Climate",t:"Why Tech Firms Are Working With Trump on Data Centers and Energy Costs",by:"Brad Plumer",th:{"Data Centers & Energy":["Power & grid"],"Politics & Elections":["Trump administration"]}},
  {d:"2026-03-04",sec:"Opinion",t:"I Worked for Block. Its A.I. Job Cuts Aren't What They Seem.",by:"Aaron Zamost",th:{"Jobs & Labor":["Layoffs & cuts"]}},
  {d:"2026-03-04",sec:"New York",t:"A.I. in New York Schools: What Lies Ahead?",by:"James Barron",th:{"Education":[]}},
  {d:"2026-03-04",sec:"Asia Pacific",t:"Where Are China's A.I. Doomers?",by:"Vivian Wang",th:{"China & Geopolitics":[],"AI Safety & Risks":["Existential & systemic"]}},
  {d:"2026-03-03",sec:"World",t:"A Fight About the Future of War",by:"Katrin Bennhold",th:{"War & Military":["Arms race & weapons"]}},
  {d:"2026-03-02",sec:"Technology",t:"OpenAI Amends A.I. Deal With the Pentagon",by:"Cade Metz, Julian E. Barnes",th:{"OpenAI":["Products & strategy"],"War & Military":["Defense contracts"]}},
  {d:"2026-03-02",sec:"Podcasts",t:"Is A.I. Creating 'Ghost GDP'?",by:"Kevin Roose, Casey Newton",th:{"Business & Economy":["Markets & finance"]}},
  {d:"2026-03-02",sec:"Podcasts",t:"The Government Wants to Punish Anthropic",by:"Casey Newton, Kevin Roose",th:{"Anthropic vs Pentagon":["Commentary & opinion"]}},
  {d:"2026-03-02",sec:"Politics",t:"Tensions Over the Iran War, Israel and A.I. Churn in a North Carolina Race",by:"Theodore Schleifer, Lisa Lerer",th:{"Politics & Elections":["Midterms & campaigns"],"War & Military":["Iran conflict"]}},
  {d:"2026-03-02",sec:"Technology",t:"The Pentagon's Favorite Tech Guy Is This Hawaiian Shirt-Wearing Founder",by:"Sheera Frenkel, Cade Metz",th:{"War & Military":["Defense contracts"]}},
  {d:"2026-03-02",sec:"New York",t:"U.S. Schools Are Betting Big on A.I. Will New York City Be Next?",by:"Troy Closson",th:{"Education":[]}},
  {d:"2026-03-02",sec:"Asia Pacific",t:"China's Parents Are Outsourcing the Homework Grind to A.I.",by:"Vivian Wang, Jiawei Wang",th:{"China & Geopolitics":[],"Education":[]}},
  {d:"2026-03-02",sec:"Asia Pacific",t:"China's New Study Buddy: The A.I. Chatbot",by:"Jiawei Wang",th:{"China & Geopolitics":[],"Education":[]}},
  {d:"2026-03-01",sec:"Technology",t:"How Talks Between Anthropic and the Defense Dept. Fell Apart",by:"Sheera Frenkel et al.",th:{"Anthropic vs Pentagon":["Negotiations & breakdown"]}},
  {d:"2026-03-01",sec:"Opinion",t:"Music, at Least, Doesn't Lie",by:"Jonathan Biss",th:{"Arts & Creative":["Visual art & design"],"Society & Culture":["Creativity & taste"]}},
  {d:"2026-03-01",sec:"Briefing",t:"A Philosopher 'Prophet'",by:"Lauren Jackson",th:{"Society & Culture":["Discourse & ideas"]}},
  {d:"2026-03-01",sec:"Business",t:"Are 'Bossware' Tools Tracking You?",by:"Lora Kelley",th:{"Jobs & Labor":["Future of work"]}},
  {d:"2026-02-28",sec:"Podcasts",t:"At the Pentagon, OpenAI is In and Anthropic Is Out",by:"Kevin Roose, Casey Newton et al.",th:{"Anthropic vs Pentagon":["Industry & politics"],"OpenAI":["Products & strategy"]}},
]

export const themeConfig: ThemeConfig[] = [
  {name:"Anthropic & Mythos", subs:["Mythos launch","Access & deployment","Government response"]},
  {name:"Anthropic vs Pentagon", subs:["Supply-chain-risk label","Negotiations & breakdown","Legal battle","Industry & politics","Commentary & opinion"]},
  {name:"OpenAI", subs:["Altman & leadership","Products & strategy"]},
  {name:"AI Industry & Models", subs:["New models & releases","Products & strategy","Benchmarks & capability","Agents","Chips & hardware"]},
  {name:"Cybersecurity & Defense", subs:["Offensive capability","Vulnerabilities & patching"]},
  {name:"War & Military", subs:["Iran conflict","Defense contracts","Drones & autonomy","Arms race & weapons"]},
  {name:"China & Geopolitics", subs:[]},
  {name:"Politics & Elections", subs:["Trump administration","Midterms & campaigns","Lobbying & money","Government use"]},
  {name:"Legal & Regulation", subs:["Courts & lawsuits","State legislation","Federal policy"]},
  {name:"Jobs & Labor", subs:["Future of work","Coders & software","Layoffs & cuts","Tiny teams","Young workers & grads"]},
  {name:"Business & Economy", subs:["Markets & finance","Startups & VC","Corporate pivots","Inequality & wealth"]},
  {name:"Data Centers & Energy", subs:["Power & grid","Local opposition","Real estate & capital"]},
  {name:"AI Safety & Risks", subs:["Model behavior","Personal harm","Existential & systemic","Interpretability & alignment"]},
  {name:"AI Misuse & Slop", subs:["Deepfakes & impersonation","Content fraud","Hallucinations & errors"]},
  {name:"Companions & Relationships", subs:[]},
  {name:"Health & Medicine", subs:[]},
  {name:"Education", subs:[]},
  {name:"Arts & Creative", subs:["Writing & publishing","Visual art & design","Performance & film"]},
  {name:"Society & Culture", subs:["Discourse & ideas","Creativity & taste","Public backlash","Young people"]},
  {name:"Daily Life & Tools", subs:[]},
]
