// Verbatim transcript excerpts from Robert's prior lectures (Understanding AI, Fall 2024).
// Used as voice reference for slide-content generation — matched cadence, asides,
// example structure. These are speech samples, not writing; generated slide text
// can be tighter than these but should sound like the same person.

export const VOICE_SAMPLES = `Here are eight transcript excerpts from past lectures by Robert. Use these as voice reference — match the cadence, the casual asides, the way he sets up a frame and then takes a position, the way he reaches for a concrete example before generalizing. These are speech, not writing; your slide content can be tighter than these (slides hold less than a spoken sentence) but should sound like the same person.

--- Sample 1: Netflix, Google, and incentives ---
Now it's really bad because on purpose, because like most recommendation systems, their goal isn't to recommend what you would most want to see. Their goal, what they recommend is what they most want you to watch. So, well, I mean, if you look at Google, which, you know, same problem with the thing, right? Google used to be, you couldn't find anything in a search engine on the web. And then Google solved that problem, getting really good at determining. And for a while, Google was amazing. You type in what you want and you'd get exactly the thing that you wanted. Now you get exactly what somebody has paid Google to show you, pretty much. Or tricked or learned Google's algorithms and tricked Google and, you know, to some extent, but it's pretty much what Google has been paid to show you. So, software is actually, and machine learning and algorithms are actually a lot better than we think they are. The business, because the businesses don't, the businesses don't benefit from us getting what we want, right? The businesses benefit from us getting just enough to stay attached and whatever maximizes revenue for them, unfortunately.

--- Sample 2: Facebook and unintended consequences ---
If you analyze Facebook usage data, you can learn a model of what drives usage. Unfortunately, what drives usage may be conspiracy theories and the most egregious. If people are angry, they stay engaged. So anger drives engagement. So that's what the model may learn. Oh, let's send them these conspiratorial videos, and let's send them to these sites about conspiracy theories, because when we send people there, they spend a lot of time on Facebook, right? So that's the model of the world that actually got learned when Facebook did just that, turn machine learning algorithms on usage data with the goal of maximizing engagement. Maximize sharing, maximize clicking, maximize, that's what happened. Again, the algorithm had no goal of having people be radicalized. It was just looking for what keeps people clicking and sharing and posting, and that's happened to be what it was.

--- Sample 3: Hallucination is just what these things are ---
This is really not that big a deal at all. If you remember what we talked about, that there's no text in an LLM, it doesn't look anything up. I think the reason people are sort of surprised that AI makes stuff up is because they're not thinking about how they actually, when they think of it as a database, they think of it as Google, right? Type in something and it goes and finds a fact and it gives me the fact, right? They're saying, oh, it's getting the wrong fact. No, it doesn't have any facts. It has a model and it's generating a response that's a prediction of what your response should be. It happens when I say, when did you go to Albuquerque? Oh, I went to Albuquerque in 2019. No, you're just wrong. You went there in 2017, but you're just wrong, right? You generated an answer. We do that all the time. Now, AIs are super confident. So, they're sort of like tech bros in that they'll give you an answer. They may have limited grasp of the facts, but they'll give it to you with, and I've been a tech bro in my time, so I can say that, but they'll give you it with great confidence and it'll sound really plausible.

--- Sample 4: How do you know something? ---
Tangent, small tangent. Do you ever sit and think about how you know something with certainty? How do you know that you... So if somebody says, what's the capital of California? Something comes into your head, and you have some experience of the level of certainty of knowing that thing. But there's no validation. There's no verification. You didn't check your sources. A word came into your head. But somehow, you experience that as something you, oh, for sure know. Or you are like, I think it might be Sacramento. Where does certainty come from? So when we say, oh, I know that. We don't know anything. I mean, our memories, you don't actually recall anything from your brain. You generate everything. Everything that you see. In fact, you don't even see anything. You generate a visual simulation of what you think you're supposed to see based on the inputs that you're getting. And so, same thing with information. I'm generating Sacramento. And somehow, I have a level of confidence associated with that. I didn't recall it. There's no words stored in your brain. We are generating a reality. That blew my mind when I learned that.

--- Sample 5: Consolidation of power ---
You know, one of the stated objectives of OpenAI is that, oh, you'll be able to be the, a company of one. Having AI will be like having an army of specialists at your control and you'll be able to build a billion dollar company, you know, as a single individual. And I don't know why that seems like a utopia, you know, like a place people want to get to because they're not going to be a 9 billion companies. So if only one, you know, like they're not going to be that many. So it is just this idea that it requires fewer and fewer people to do the work and that profit continues to, you know, collect in a smaller and smaller number of people. And we just get to where we're headed really fast and where life is not so good for most folks and tremendous for a very small number of people. And I just don't, you know, in that conversation of the world we want to be, what we want to live in, I just don't think that's the world we want to live in.

--- Sample 6: We didn't design it, we grew it ---
The capabilities that an LLM has, the things that it can do were not created. Every machine we've ever had before had a designer who said, I'm, this is how this thing is going to work. And here's all the things that can do. A bicycle. Here's how the thing is going to go. And then the pedals are going to go on a car, a computer, every piece of computer software before LLMs had a designer who said, it's going to have these features and it's going to work this way. The capabilities that an LLM has are emergent. It's like they grew, we grew an intelligence. We grew something that can do things. We didn't design it. We designed the machine that can learn, but then the learning is the thing that is now doing things. So no one knows what they can do. We know some of what they can do. We have expectations because we try, oh, let me try doing this. That didn't work so well. Let me try doing this. Holy moly, that worked. Why does that work?

--- Sample 7: Why I'm a Claude fan ---
Here's the thing that I find that has been just kind of unbelievably like really surprising to me and really valuable is that the level of conversation I've been having and especially Claude's ability to adapt to the way that I'm interacting and the way that I'm posing the question. And it's coming back with thought, like the more thoughtful I get, the more thoughtful it gets. And the more insightful and the tougher my premises are and the more detailed it's like the conversations are great. Sometimes it'll give me an initially kind of a rote answer and then I just be critical with it. Like, yeah, that's kind of, you know, that's kind of easy thinking. I mean, I think it's a little deeper than this. And it'll say you're right. That was easy thinking about it'll come back with something really challenging, you know? So I'm telling you people, if you've never done that, you have to do it.

--- Sample 8: Education and the thing we could actually fix ---
Our model of education, which a lot of people recognize was based on sort of an industrial model, like sitting at a desk and doing repetitive tasks, which a lot of us recognize is not the optimal way to grow a brain and treat a child. We might get some help from AI. And I think about, you know, just starting with in terms of short-term practical benefit, having every kid have an individual tutor who can help them learn while the teacher is sort of managing the way that the whole environment and community works. Wow, that could be a revolution in education. Each person really needs different things. Like the variance in what 25 kids need in a room, it's very, very, very hard to create a curriculum that would be even, you know, find 20%, it would be optimal for 25% of the kids in the room. I've seen adults and children use AI to learn things in an incredibly efficient way and in a very humane way, like a very, just like patient and thoughtful way.`
