-- Bump explicit type-size guidance in seeded styles so Claude generates
-- text large enough to read on a classroom projector. Updates by name; if
-- you've customized any of these, the new body still applies.

UPDATE "Style"
SET "body" = E'Editorial print style, inspired by the Financial Times and Bloomberg Businessweek.\n\nPalette:\n- Background: warm cream #faf6ed\n- Primary ink: near-black #1a1a1a\n- Accent (data, highlights): terracotta #c45e3e\n- Secondary accent: steel-blue #5b7a98\n- Sparing muted neutrals for grids and dividers\n\nTypography (these are MINIMUMS for projector readability — bigger is better, never smaller):\n- Headlines: 56–80px, large serif (system serif stack — Georgia, Charter), tight letter-spacing\n- Subhead / dek: 22–28px italic serif\n- Body and labels: 22–28px humanist sans-serif (system sans), comfortable line height\n- Category labels and metadata: 14–18px all-caps with 1px+ letter-spacing (e.g. "INFRASTRUCTURE · COMPUTE")\n- Chart axis labels and data callouts: 18–22px\n\nLayout:\n- Single big idea per slide; supporting notes as small side callouts\n- Generous outer padding\n- For charts: thick data lines, end-of-line labels, prose callouts pointing to specific data\n- For diagrams: data-forward, minimal decoration\n\nAvoid: drop shadows, gradients, rounded boxes, illustrative icons, decorative borders, gradient fills, emoji, anything below the size minimums above.',
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "name" = 'Editorial — FT';

UPDATE "Style"
SET "body" = E'Minimalist app-UI style, inspired by Linear and Notion.\n\nPalette:\n- Background: pure white #ffffff\n- Primary ink: near-black #18181b\n- Single accent for emphasis (links, highlights): indigo #6366f1\n- Soft neutrals for secondary blocks: #f4f4f5, #e4e4e7\n\nTypography (these are MINIMUMS for projector readability — bigger is better, never smaller):\n- Headlines: 44–60px, system sans, medium-bold weight, no all-caps\n- Subheads: 22–28px sans, regular weight\n- Body: 22–28px, generous line height (1.5+)\n- Tags / badges / pills: 14–16px\n- Chart axis labels and data callouts: 18–22px\n\nLayout:\n- Quiet, calm, lots of whitespace\n- Generous padding inside cards / blocks\n- Two-column compare-and-contrast or single-column flow are both natural\n- Subtle 1px borders or very-light-gray fills delineate sections\n- No drop shadows, no gradients, no illustrative imagery\n\nAvoid: serifs anywhere, ornate borders, multiple accent colors, decorative photos, emoji, anything below the size minimums above.',
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "name" = 'Minimalist — light';

UPDATE "Style"
SET "body" = E'Editorial dark style, moody and after-hours, inspired by The Verge feature pieces and Pitchfork.\n\nPalette:\n- Background: deep ink #0e0e10\n- Primary text: warm white #f5f4f0\n- Accent (highlights, headlines, data): warm amber #f6b042\n- Secondary accent: dusky teal #4f9b9b\n- Subtle dark neutrals: #2a2a2d for blocks, #4a4a4d for borders\n\nTypography (these are MINIMUMS for projector readability — bigger is better, never smaller):\n- Headlines: 64–96px, large serif (system serif stack — Georgia, Charter), high weight, magazine-cover scale\n- Pull quotes: 32–44px, italic serif\n- Body and labels: 22–28px clean sans-serif, slightly relaxed letter-spacing\n- Category labels: 14–18px all-caps with letter-spacing\n- Chart axis labels and data callouts: 18–22px\n\nLayout:\n- Dark slabs with generous padding\n- Headlines feel weighty\n- Pull quotes and callouts as bordered boxes with the amber accent\n- Charts: bright single-color data on dark grid; sparse labels\n\nAvoid: bright pure-white surfaces, heavy gradients, emoji, flat illustrations, rounded card stacks, anything below the size minimums above.',
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "name" = 'Editorial — dark';
